version: '3.8'
services:
  # shard 0
  shard0-replica0: &shard0
    build:
      context: mongod
    command: mongod -f /etc/mongod.conf --shardsvr --replSet shard0
    volumes:
      - ./mongod/mongod.conf:/etc/mongod.conf
    networks:
      internalnetwork:
        aliases:
          - shard0-replica0
    environment:
      - REPSET_NAME=shard0
    expose:
      - "27017"

  shard0-replica1:
    <<: *shard0
    networks:
      internalnetwork:
        aliases:
          - shard0-replica1

  shard0-replica2:
    <<: *shard0
    networks:
      internalnetwork:
        aliases:
          - shard0-replica2

  # shard 1
  shard1-replica0: &shard1
    build:
      context: mongod
    command: mongod -f /etc/mongod.conf --shardsvr --replSet shard1
    volumes:
      - ./mongod/mongod.conf:/etc/mongod.conf
    networks:
      internalnetwork:
        aliases:
          - shard1-replica0
    environment:
      - REPSET_NAME=shard1
    expose:
      - "27017"

  shard1-replica1:
    <<: *shard1
    networks:
      internalnetwork:
        aliases:
          - shard1-replica1

  shard1-replica2:
    <<: *shard1
    networks:
      internalnetwork:
        aliases:
          - shard1-replica2

  # config db
  configdb-replica0: &configdb
    build:
      context: mongod
    command: mongod -f /etc/mongod.conf --configsvr --replSet configdb
    volumes:
      - ./mongod/mongod.conf:/etc/mongod.conf
    networks:
      internalnetwork:
        aliases:
          - configdb-replica0
    environment:
      - REPSET_NAME=configdb
    expose:
      - "27017"

  configdb-replica1:
    <<: *configdb
    networks:
      internalnetwork:
        aliases:
          - configdb-replica1

  configdb-replica2:
    <<: *configdb
    networks:
      internalnetwork:
        aliases:
          - configdb-replica2

  # router
  router:
    build:
      context: mongos
    command: mongos --port 27017 --bind_ip 0.0.0.0 --configdb "configdb/configdb-replica0:27017,configdb-replica1:27017,configdb-replica2:27017"
    depends_on:
      - shard0-replica0
      - shard0-replica1
      - shard0-replica2
      - shard1-replica0
      - shard1-replica1
      - shard1-replica2
      - configdb-replica0
      - configdb-replica1
      - configdb-replica2
    volumes:
      - ./dump:/dump
    networks:
      internalnetwork:
        aliases:
          - router
    environment:
      - SHARD_LIST=shard0/shard0-replica0:27017,shard0-replica1:27017,shard0-replica2:27017;shard1/shard1-replica0:27017,shard1-replica1:27017,shard1-replica2:27017
    expose:
      - "27017"
    ports:
      - "27017:27017"

networks:
  internalnetwork: {}
